name: CI-CD-Pileline-aws

env:
  EB_PACKAGE_S3_BUCKET_NAME: "oleksii-kozlov-flask-test-bucket"
  EB_APPLICATION_NAME: "FlaskTest"
  EB_ENVIRONMENT: "Flasktest-env"
  DEPLOY_PACKAGE_NAME: "flask_test_${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-central"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        
      - name: Create ZIP package
        run: zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
        
      
