name: CI-CD-Pileline-aws

env:
  EB_PACKAGE_S3_BUCKET_NAME: "oleksii-kozlov-flask-test-bucket"
  EB_APPLICATION_NAME: "FlaskTest"
  EB_ENVIRONMENT: "Flasktest-env"
  DEPLOY_PACKAGE_NAME: "flask_test_${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-central"

on:
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
      id-token: write
      contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        
      - name: Create ZIP package
        run: zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
          
      - name: Copy deployment package to S3
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
